350Project/Controllers/gALLERYController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _350Project.Models;
using _350Project.Processor;

namespace _350Project.Controllers
{
    public class GalleryController : Controller
    {
        [HttpGet]
        public ActionResult AddImage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddImage(ImageModel model)
        {
            string filename = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
            string extension = Path.GetExtension(model.ImageFile.FileName);

            filename = filename + DateTime.Now.ToString("yymmssfff") + extension;

            model.ImagePath = "~/Image/"+ filename;

            filename = Path.Combine(Server.MapPath("~/Image/"),filename);

            model.ImageFile.SaveAs(filename);

            HomeProcessor.UploadImage(model);

            TempData["Message"] = "Update success";

            return RedirectToAction("Index", "Dashboard");
        }
    }
}

350Project/Views/Gallery/AddImage.cshtml
@model _350Project.Models.ImageModel

@{
    ViewBag.Title = "AddImage";
}

<div class="row mt-5 justify-content-between">

    <button onclick="location.href='/Dashboard/Index'" type="button" class="btn btn-primary">
        < Back to dashboard
    </button>

    <h2>AddImage</h2>
</div>


@using (Html.BeginForm("AddImage", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
}